### ISSUE TITLE
[Issue] 'Options' object has no attribute 'prompt_attention'

### ISSUE THREAD

**Issue by VRArt1** [acorderob/sd-webui-sendtonegative#2]
## Current Behavior

Not currently functioning.
## Expected Behavior

Functioning.
## Failure Information (for bugs)

When trying to utilize sendtonegative the error at the bottom is logged.

## Steps to Reproduce

1. Insert a negative prompt into the positive prompt area with the correct formatting. I.E. <!prompt!>
2. Click generate.

## Context

No special utilization or oddities from what I can tell.

- WebUI used and version:
 [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)

## Failure Logs

`*** Error running process: C:\Users\vrart\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-sendtonegative\scripts\extension.py
    Traceback (most recent call last):
      File "C:\Users\vrart\Desktop\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
      File "C:\Users\vrart\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-sendtonegative\scripts\extension.py", line 34, in process
        stn = SendToNegative(self.__logstn, opts=opts)
      File "C:\Users\vrart\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-sendtonegative\sendtonegative.py", line 38, in __init__
        if opts is not None and opts.prompt_attention == "Compel parser":
      File "C:\Users\vrart\Desktop\AI\stable-diffusion-webui\modules\shared.py", line 617, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'prompt_attention'`

**Comment by acorderob** [comment]
That property exists in SD.Next but not in A1111. I will add a better check asap. Thanks for the report.

**Comment by acorderob** [comment]
It should be fixed now. Please test.
